### ISSUE TITLE
HUZZAH ESP8266 Compatibility

### ISSUE THREAD

**Issue by mandreko** [Bucknalla/kicad-feather-wing-template#1]
Firstly, I love this.

I was making a custom feather wing for my project, and my board didn't fit perfectly, so I was trying this. I noticed that the pin layout didn't match my HUZZAH ESP8266 board. While the pin layout matches Adafruit's specifications, it looks like for the ESP8266 board specifically, they have re-ordered some pins slightly. https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/pinouts

It might be worth adding a note that for ESP8266 boards, this will fit, but the silkscreen will be wrong, which could cause issues. Not sure if it's worth the effort or not, but figured I'd add this ;)

**Comment by Bucknalla** [comment]
Thanks @mandreko :) I'll add a note for the ESP8266
